# Set all versions
CUSTOM_BUILD_TYPE ?= ALPHA

CUSTOM_DATE_YEAR := $(shell date -u +%Y)
CUSTOM_DATE_MONTH := $(shell date -u +%m)
CUSTOM_DATE_DAY := $(shell date -u +%d)
CUSTOM_DATE_HOUR := $(shell date -u +%H)
CUSTOM_DATE_MINUTE := $(shell date -u +%M)
CUSTOM_BUILD_DATE_UTC := $(shell date -d '$(CUSTOM_DATE_YEAR)-$(CUSTOM_DATE_MONTH)-$(CUSTOM_DATE_DAY) $(CUSTOM_DATE_HOUR):$(CUSTOM_DATE_MINUTE) UTC' +%s)
CUSTOM_BUILD_DATE := $(CUSTOM_DATE_YEAR)$(CUSTOM_DATE_MONTH)$(CUSTOM_DATE_DAY)-$(CUSTOM_DATE_HOUR)$(CUSTOM_DATE_MINUTE)

CUSTOM_PLATFORM_VERSION := 10.0

CUSTOM_ARTSTAR_VERSION := Summer

CUSTOM_DATE_CODE := $(CUSTOM_DATE_HOUR)$(CUSTOM_DATE_MINUTE)

TARGET_PRODUCT_SHORT := $(subst artstar_,,$(CUSTOM_BUILD))

CUSTOM_VERSION := ArtStarOS-$(CUSTOM_BUILD)-$(CUSTOM_PLATFORM_VERSION)-$(CUSTOM_DATE_CODE)-$(CUSTOM_BUILD_TYPE)
CUSTOM_VERSION_PROP := 10

CUSTOM_PROPERTIES := \
    ro.artstar.version=$(CUSTOM_VERSION_PROP) \
    ro.artstar.version.display=$(CUSTOM_VERSION) \
    ro.artstar.build_date=$(CUSTOM_BUILD_DATE) \
    ro.artstar.build_date_utc=$(CUSTOM_BUILD_DATE_UTC) \
    ro.artstar.build_type=$(CUSTOM_BUILD_TYPE) \
    ro.artstar.custom_version=$(CUSTOM_ARTSTAR_VERSION)

ifeq ($(CUSTOM_BUILD_TYPE), OFFICIAL)
PRODUCT_DEFAULT_DEV_CERTIFICATE := vendor/secure/releasekey
endif
